config:
  replacements:
    - repo_mappings:
        opendatahub/odh-ai-first-demo: opendatahub/odh-ai-first-demo
  supported-ocp-versions:
    build:
      - name: v4.20
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20
    release:
      - v4.20
